from PyQt6.QtWidgets import*
app = QApplication([])
window = QWidget()
window.resize(700,500)
main_line = QVBoxLayout()
h1 = QHBoxLayout()
h2 = QHBoxLayout()
h3 = QHBoxLayout()
h4 = QHBoxLayout()
wikno = QLineEdit()
plus_btn = QPushButton("+")
minys_btn = QPushButton("-")
dilenya_btn = QPushButton(":")
mnogennya_btn = QPushButton("*")
odun_btn = QPushButton("1")
dwa_btn = QPushButton("2")
tru_btn = QPushButton("3")
choturu_btn = QPushButton("4")
five_btn = QPushButton("5")
six_btn = QPushButton("6")
seven_btn = QPushButton("7")
visim_btn = QPushButton("8")
nine_btn = QPushButton("9")
zero_btn = QPushButton("0")
tochka_btn = QPushButton(".")
answer_btn = QPushButton("=")
main_line.addWidget(wikno)
h1.addWidget(seven_btn)
h1.addWidget(visim_btn)
h1.addWidget(nine_btn)
h1.addWidget(dilenya_btn)
main_line.addLayout(h1)
h2.addWidget(choturu_btn)
h2.addWidget(five_btn)
h2.addWidget(six_btn)
h2.addWidget(mnogennya_btn)
main_line.addLayout(h2)
h3.addWidget(odun_btn)
h3.addWidget(dwa_btn)
h3.addWidget(tru_btn)
h3.addWidget(minys_btn)
main_line.addLayout(h3)
h4.addWidget(zero_btn)
h4.addWidget(plus_btn)
h4.addWidget(tochka_btn)
h4.addWidget(answer_btn)
main_line.addLayout(h4)

def plus_funk():
    text = wikno.text()
    text += '+'
    wikno.setText(text)

plus_btn
window.setLayout(main_line)
window.show()
app.exec()